### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by ShinichiNakajima** [ShinichiNakajima/protospace-36481#1]
https://protospace-36481.herokuapp.com/

**Comment by miyu-yamamoto** [comment]
@ShinichiNakajima さん、お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう。**
現状、エラー画面が表示されます
<img width="718" alt="スクリーンショット 2021-09-27 10 42 05" src="https://user-images.githubusercontent.com/59544869/134833602-ea6bfc5b-5d7e-4058-9096-3b09e45973e4.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by ShinichiNakajima** [comment]
承知いたしました！

**Comment by miyu-yamamoto** [comment]
@ShinichiNakajima さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by ShinichiNakajima** [comment]
了解です！ありがとうございました！
